Algoritmo "competir"
// Disciplina   : Programação e algoritmos
// Autor(a)    : João Victor Da Silva Jardim
// Data atual  : 20/06/2021

Var
idade, altura:real

Inicio
escreval ("Digite sua idade: ")
leia(idade)
escreval ("Digite sua altura: ")
leia(altura)

se (idade>=18) e (altura>=1.75) entao

   escreval ("Você poderá competir.")

senao

     escreval ("Você não poderá competir.")

fimse

fimalgoritmo